name: verificar

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar script de evaluacion
        run: node script.js
